/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_expotec;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author anerm
 */
public class Selección_Carrera extends javax.swing.JFrame {

    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JPanel panelCarreras;
    private javax.swing.JButton btnSeleccionarCarrera;
    private Map<String, String[]> datosCarreras;

    private final Color GRIS_CELDA = new Color(215, 215, 215);
    private final Color MORADO_CELDA = new Color(54, 25, 60);

    public Selección_Carrera() {
        setUndecorated(false);
        initComponents();
        inicializarDatos();
        configurarComponentesDinamicos();
        actualizarCuadranteCarreras();

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                redimensionar();
            }
        });

        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                redimensionar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SeleccionarCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 234, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(969, 553));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 27, 46));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        jPanel6.setBackground(new java.awt.Color(30, 27, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(67, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/imagen_66x47.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(562, 562, 562)
                    .addComponent(jLabel10)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel10)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1190, 70));

        jPanel7.setBackground(new java.awt.Color(244, 239, 245));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(765, 370));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 37, 80));
        jLabel6.setText("¿Qué carrera deseas elegir?");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Selecciona el área y la carrera universitaria que quieras empezar a preparar:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 37, 80));
        jLabel8.setText("Carreras:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 118, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 37, 80));
        jLabel11.setText("Filtrar por Área de estudio:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        SeleccionarCarrera.setBackground(new java.awt.Color(255, 107, 26));
        SeleccionarCarrera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SeleccionarCarrera.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionarCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        SeleccionarCarrera.setText("Seleccionar Carrera");
        SeleccionarCarrera.setBorder(null);
        SeleccionarCarrera.setBorderPainted(false);
        SeleccionarCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SeleccionarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarCarreraActionPerformed(evt);
            }
        });
        jPanel7.add(SeleccionarCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 160, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 106, 940, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selección_Carrera().setVisible(true);
            }
        });
    }

    private void configurarComponentesDinamicos() {
        jPanel7.setLayout(null);

        btnSeleccionarCarrera = new javax.swing.JButton("Seleccionar carrera");

        btnSeleccionarCarrera.setFont(new Font("Arial", Font.BOLD, 16));
        btnSeleccionarCarrera.setBackground(new Color(54, 25, 60));
        btnSeleccionarCarrera.setForeground(Color.WHITE);

        btnSeleccionarCarrera.setFocusPainted(false);

        btnSeleccionarCarrera.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                System.out.println("Carrera seleccionada");

            }
        });

        jPanel7.add(btnSeleccionarCarrera);

        String[] categorias = {"Humanidades", "Económicas", "Ingenierías", "Salud", "Educación"};
        comboFiltro = new javax.swing.JComboBox<>(categorias);
        comboFiltro.setFont(new Font("Arial", Font.PLAIN, 14));
        comboFiltro.setBackground(Color.WHITE);

        comboFiltro.setBounds(60, 145, 585, 35);

        jPanel7.add(comboFiltro, 0);

        panelCarreras = new javax.swing.JPanel();
        panelCarreras.setLayout(null);
        panelCarreras.setBackground(new java.awt.Color(244, 239, 245));

        panelCarreras.setBounds(60, 265, 585, 130);

        jPanel7.add(panelCarreras, 0);

        comboFiltro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                actualizarCuadranteCarreras();
            }
        });

        jPanel7.removeAll();

        jPanel7.add(jLabel6);
        jPanel7.add(jLabel7);
        jPanel7.add(jLabel8);
        jPanel7.add(jLabel11);

        jPanel7.add(comboFiltro);
        jPanel7.add(panelCarreras);
        jPanel7.add(btnSeleccionarCarrera);

        jPanel7.revalidate();
        jPanel7.repaint();
    }

    private void redimensionar() {
        int ancho = getContentPane().getWidth();
        int alto = getContentPane().getHeight();

        jPanel1.setBounds(0, 0, ancho, alto);
        jPanel1.setPreferredSize(new java.awt.Dimension(ancho, alto));
        jPanel1.setLayout(null);

        jPanel2.setBounds(0, 0, ancho, 70);
        jPanel6.setBounds(0, alto - 70, ancho, 70);

        int anchoPanel = (int) (ancho * 0.70);
        int altoPanel = (int) (alto * 0.65);

        int xPanel = (ancho - anchoPanel) / 2;
        int yPanel = (alto - altoPanel) - 180;
        jPanel7.setBounds(xPanel, yPanel, anchoPanel, altoPanel);
        jPanel7.setLayout(null);

        int anchoInput = (int) (anchoPanel * 0.62);
        int xInput = (anchoPanel - anchoInput) / 2;

        // Título
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, (int) (anchoPanel * 0.038)));
        jLabel6.setBounds(0, (int) (altoPanel * 0.07), anchoPanel, (int) (altoPanel * 0.12));

        // Subtítulo
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, (int) (anchoPanel * 0.015)));
        jLabel7.setBounds(0, (int) (altoPanel * 0.20), anchoPanel, (int) (altoPanel * 0.06));

        // Label "Filtrar por Área de estudio:"
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, (int) (anchoPanel * 0.020)));
        jLabel11.setBounds(xInput, (int) (altoPanel * 0.28), anchoInput, (int) (altoPanel * 0.07));

        // ComboBox
        if (comboFiltro != null) {
            comboFiltro.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, (int) (anchoPanel * 0.015)));
            comboFiltro.setBounds(xInput, (int) (altoPanel * 0.37), anchoInput, (int) (altoPanel * 0.09));
        }

        // Label "Carreras:"
        jLabel8.setFont(new java.awt.Font("Arial", 0, (int) (anchoPanel * 0.020)));
        jLabel8.setBounds(xInput, (int) (altoPanel * 0.52), anchoInput, (int) (altoPanel * 0.07));

        // Panel cuadrante de carreras
        if (panelCarreras != null) {

            int panelY = (int) (altoPanel * 0.62);
            int panelAlto = (int) (altoPanel * 0.18);

            panelCarreras.setBounds(
                    xInput,
                    panelY,
                    anchoInput,
                    panelAlto
            );

            if (btnSeleccionarCarrera != null) {

                btnSeleccionarCarrera.setBounds(
                        535,
                        (int) (altoPanel * 0.84), // posición vertical
                        275,
                        (int) (altoPanel * 0.10) // altura
                );

                btnSeleccionarCarrera.setFont(
                        new Font(
                                "SansSerif",
                                Font.BOLD,
                                (int) (altoPanel * 0.030)
                        )
                );
            }

            // Posiciones de labels
            int espacio = 20;

            int anchoLabel = (anchoInput - (espacio * 2)) / 3;

            int altoLabel = panelAlto - 10;

            for (int i = 0; i < panelCarreras.getComponentCount(); i++) {

                java.awt.Component c = panelCarreras.getComponent(i);

                c.setBounds(
                        i * (anchoLabel + espacio), // x
                        0, // y
                        anchoLabel,
                        60
                );
            }
        }

        jPanel7.revalidate();
        jPanel7.repaint();
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * Aplica un factor de escala a un valor base y devuelve int.
     */
    private int escalar(int valorBase, double factor) {
        return (int) Math.round(valorBase * factor);
    }

    private void inicializarDatos() {
        datosCarreras = new HashMap<>();
        datosCarreras.put("Humanidades", new String[]{"Filosofía", "Letras Clásicas", "Historia"});
        datosCarreras.put("Económicas", new String[]{"Administración de Empresas", "Economía", "Contaduría Pública"});
        datosCarreras.put("Ingenierías", new String[]{"Ingeniería en Sistemas", "Ingeniería Civil", "Ingeniería Industrial"});
        datosCarreras.put("Salud", new String[]{"Medicina General", "Enfermería", "Nutrición"});
        datosCarreras.put("Educación", new String[]{"Pedagogía", "Educación Primaria", "Psicopedagogía"});
    }

    private void actualizarCuadranteCarreras() {

        if (panelCarreras == null) {
            return;
        }

        panelCarreras.removeAll();

        if (comboFiltro.getSelectedItem() == null) {
            return;
        }

        String seleccion = (String) comboFiltro.getSelectedItem();
        String[] carreras = datosCarreras.get(seleccion);

        Color[] fondos = {
            MORADO_CELDA,
            Color.WHITE,
            MORADO_CELDA
        };

        Color[] textos = {
            Color.WHITE,
            new Color(45, 37, 80),
            Color.WHITE
        };

        if (carreras != null) {

            for (int i = 0; i < carreras.length; i++) {

                JLabel lblCarrera = new JLabel(carreras[i]);

                lblCarrera.setHorizontalAlignment(SwingConstants.CENTER);
                lblCarrera.setVerticalAlignment(SwingConstants.CENTER);

                lblCarrera.setFont(new Font("Arial", Font.BOLD, 18));

                lblCarrera.setOpaque(true);

                lblCarrera.setBackground(fondos[i]);
                lblCarrera.setForeground(textos[i]);

                lblCarrera.setBounds(
                        0,
                        0,
                        150,
                        60
                );

                panelCarreras.add(lblCarrera);
            }
        }

        redimensionar();

        panelCarreras.revalidate();
        panelCarreras.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeleccionarCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
