/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_expotec;

/**
 *
 * @author anerm
 */
public class ÁreasCurriculares extends javax.swing.JFrame {

    private javax.swing.JLabel labelTitulo;
    private javax.swing.JComboBox<String> combo1mer;
    private javax.swing.JComboBox<String> combo2do;
    private javax.swing.JComboBox<String> combo3cer;
    private javax.swing.JComboBox<String> combo4to;
    private javax.swing.JComboBox<String> combo5to;
    private javax.swing.JComboBox<String> comboSubtitulo;
    private javax.swing.JLabel labelAnio1;
    private javax.swing.JLabel labelAnio2;
    private javax.swing.JLabel labelAnio3;
    private javax.swing.JLabel labelAnio4;
    private javax.swing.JLabel labelAnio5;
    private javax.swing.JButton btnIniciar;

    /**
     * Creates new form ÁreasCurriculares
     */
    private String carreraSeleccionada;

    public ÁreasCurriculares(String carrera) {

        this.carreraSeleccionada = carrera;

        initComponents();

        configurarComboAreas();

        seleccionarCarreraInicial();

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getContentPane().setLayout(null);

        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                redimensionar();
            }
        });

        javax.swing.SwingUtilities.invokeLater(() -> {
            redimensionar();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(238, 234, 248));
        jPanel5.setPreferredSize(new java.awt.Dimension(970, 560));

        jPanel6.setBackground(new java.awt.Color(30, 27, 46));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Áreas Curriculares");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(1019, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(30, 27, 46));
        jPanel7.setPreferredSize(new java.awt.Dimension(67, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(1184, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(244, 239, 245));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel8.setPreferredSize(new java.awt.Dimension(765, 370));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(986, 986, 986)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel9)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÁreasCurriculares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÁreasCurriculares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÁreasCurriculares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÁreasCurriculares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ÁreasCurriculares("Salud").setVisible(true);
            }
        });
    }

    private void configurarComboAreas() {

        int anchoCombo = 400;
        int xCombo = (977 - anchoCombo) / 2;

        labelTitulo = new javax.swing.JLabel();
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelTitulo.setFont(
                new java.awt.Font(
                        "SansSerif",
                        java.awt.Font.BOLD,
                        28
                )
        );

        labelTitulo.setForeground(
                new java.awt.Color(
                        45,
                        37,
                        80
                )
        );

        labelTitulo.setBounds(
                250,
                20,
                500,
                55
        );

        jPanel8.setLayout(null);

        jPanel8.add(labelTitulo);

        // ── Posiciones base ──
        int anchoColumna = 160;
        int separacion = 20;
        int x1 = 50;
        int x2 = x1 + anchoColumna + separacion;
        int x3 = x2 + anchoColumna + separacion;
        int x4 = x3 + anchoColumna + separacion;
        int x5 = x4 + anchoColumna + separacion;

        // ── Label y ComboBox 1er Año ──
        labelAnio1 = new javax.swing.JLabel("  1er Año");
        labelAnio1.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 20));
        labelAnio1.setForeground(new java.awt.Color(45, 37, 80));
        labelAnio1.setBackground(new java.awt.Color(208, 197, 228));
        labelAnio1.setOpaque(true);
        labelAnio1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2));
        labelAnio1.setBounds(x1, 120, anchoColumna, 25);
        jPanel8.add(labelAnio1);

        String[] materias1mer = {
            "Química",
            "Física",
            "Biología celular y molecular"
        };

        combo1mer = new javax.swing.JComboBox<>(materias1mer);
        combo1mer.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 20));
        combo1mer.setForeground(new java.awt.Color(45, 37, 80));
        combo1mer.setBackground(java.awt.Color.WHITE);
        combo1mer.setBounds(x1, 150, anchoColumna, 30);
        jPanel8.add(combo1mer);

        // ── Label y ComboBox 2do Año ──
        labelAnio2 = new javax.swing.JLabel("  2do Año");
        labelAnio2.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 20));
        labelAnio2.setForeground(new java.awt.Color(45, 37, 80));
        labelAnio2.setBackground(new java.awt.Color(208, 197, 228));
        labelAnio2.setOpaque(true);
        labelAnio2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2));
        labelAnio2.setBounds(x2, 120, anchoColumna, 25);
        jPanel8.add(labelAnio2);

        String[] materias2do = {
            "Anatomía Humana",
            "Histología u Embriología",
            "Bioquímica",
            "Fisiología"
        };

        combo2do = new javax.swing.JComboBox<>(materias2do);
        combo2do.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        combo2do.setForeground(new java.awt.Color(45, 37, 80));
        combo2do.setBackground(java.awt.Color.WHITE);
        combo2do.setBounds(x2, 150, anchoColumna, 30);
        jPanel8.add(combo2do);

        // ── Label y ComboBox 3cer Año ──
        labelAnio3 = new javax.swing.JLabel("   3cer Año");
        labelAnio3.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        labelAnio3.setForeground(new java.awt.Color(45, 37, 80));
        labelAnio3.setBackground(new java.awt.Color(208, 197, 228));
        labelAnio3.setOpaque(true);
        labelAnio3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2));
        labelAnio3.setBounds(x3, 120, anchoColumna, 25);
        jPanel8.add(labelAnio3);

        String[] materias3cer = {
            "Patología",
            "Física",
            "Biología celular y molecular",
            "Psicología"
        };

        combo3cer = new javax.swing.JComboBox<>(materias3cer);
        combo3cer.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        combo3cer.setForeground(new java.awt.Color(45, 37, 80));
        combo3cer.setBackground(java.awt.Color.WHITE);
        combo3cer.setBounds(x3, 150, anchoColumna, 30);
        jPanel8.add(combo3cer);

        // ── Label y ComboBox 4to Año ──
        labelAnio4 = new javax.swing.JLabel("   4to Año");
        labelAnio4.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        labelAnio4.setForeground(new java.awt.Color(45, 37, 80));
        labelAnio4.setBackground(new java.awt.Color(208, 197, 228));
        labelAnio4.setOpaque(true);
        labelAnio4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2));
        labelAnio4.setBounds(x4, 120, anchoColumna, 25);
        jPanel8.add(labelAnio4);

        String[] materias4to = {
            "Química",
            "Física",
            "Biología celular y molecular",
            "Psicología"
        };

        combo4to = new javax.swing.JComboBox<>(materias4to);
        combo4to.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        combo4to.setForeground(new java.awt.Color(45, 37, 80));
        combo4to.setBackground(java.awt.Color.WHITE);
        combo4to.setBounds(x4, 150, anchoColumna, 30);
        jPanel8.add(combo4to);

        // ── Label y ComboBox 5to Año ──
        labelAnio5 = new javax.swing.JLabel("   5to Año");
        labelAnio5.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        labelAnio5.setForeground(new java.awt.Color(45, 37, 80));
        labelAnio5.setBackground(new java.awt.Color(208, 197, 228));
        labelAnio5.setOpaque(true);
        labelAnio5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE, 2));
        labelAnio5.setBounds(x5, 120, anchoColumna, 25);
        jPanel8.add(labelAnio5);

        String[] materias5to = {
            "Química",
            "Física",
            "Biología celular y molecular",
            "Psicología"
        };

        combo5to = new javax.swing.JComboBox<>(materias5to);
        combo5to.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        combo5to.setForeground(new java.awt.Color(45, 37, 80));
        combo5to.setBackground(java.awt.Color.WHITE);
        combo5to.setBounds(x5, 150, anchoColumna, 30);
        jPanel8.add(combo5to);

        String[] subtitulos = {
            "Ciencias Básicas y biológicas",
            "Ciencias sociales y salud pública",
            "Ciencias Clínicas",
            "Investigación"
        };

        comboSubtitulo = new javax.swing.JComboBox<>(subtitulos);
        comboSubtitulo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        comboSubtitulo.setForeground(new java.awt.Color(45, 37, 80));
        comboSubtitulo.setBackground(new java.awt.Color(244, 239, 245));
        comboSubtitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        comboSubtitulo.setBounds(375, 75, 350, 35);
        jPanel8.add(comboSubtitulo);

        btnIniciar = new javax.swing.JButton("Iniciar");
        btnIniciar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        btnIniciar.setForeground(java.awt.Color.WHITE);
        btnIniciar.setBackground(new java.awt.Color(68, 22, 61)); // #44163D
        btnIniciar.setFocusPainted(false);
        btnIniciar.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(104, 89, 151), 2, true));
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                Carrera carrera = new Carrera();
                carrera.setVisible(true);

                dispose(); // Cierra la ventana actual
            }
        });

        jPanel8.add(btnIniciar);

        jPanel8.revalidate();
        jPanel8.repaint();

        comboSubtitulo.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                actualizarVisibilidadCombos();
                actualizarMateriasPorSubtitulo();
            }
        });

        actualizarVisibilidadCombos();
    }

    private void seleccionarCarreraInicial() {

        if (carreraSeleccionada == null) {
            return;
        }

        labelTitulo.setText(
                "Áreas Curriculares: " + carreraSeleccionada
        );

        actualizarContenidoPorCarrera();
    }

    private void actualizarMateriasPorSubtitulo() {

        if (comboSubtitulo == null) {
            return;
        }

        String seleccion
                = (String) comboSubtitulo.getSelectedItem();

        if (seleccion == null) {
            return;
        }

        String[] m1;
        String[] m2;
        String[] m3;
        String[] m4;
        String[] m5;

        switch (seleccion) {

            case "Ciencias Básicas y biológicas":

                m1 = new String[]{
                    "Química",
                    "Física",
                    "Biología celular"
                };

                m2 = new String[]{
                    "Anatomía",
                    "Histología",
                    "Bioquímica"
                };

                m3 = new String[]{
                    "Patología",
                    "Microbiología"
                };

                m4 = new String[]{
                    "Medicina Interna"
                };

                m5 = new String[]{
                    "Ginecología"
                };

                break;

            case "Ciencias sociales y salud pública":

                m1 = new String[]{
                    "Psicología"
                };

                m2 = new String[]{
                    "Salud Pública"
                };

                m3 = new String[]{
                    "Epidemiología"
                };

                m4 = new String[]{};

                m5 = new String[]{};

                break;

            case "Ciencias Clínicas":

                m1 = new String[]{
                    "Propedéutica"
                };

                m2 = new String[]{
                    "Semiología"
                };

                m3 = new String[]{
                    "Diagnóstico"
                };

                m4 = new String[]{
                    "Cirugía"
                };

                m5 = new String[]{
                    "Especialidades"
                };

                break;

            case "Investigación":

                m1 = new String[]{
                    "Investigación I"
                };

                m2 = new String[]{
                    "Investigación II"
                };

                m3 = new String[]{
                    "Metodología"
                };

                m4 = new String[]{
                    "Tesis I"
                };

                m5 = new String[]{
                    "Tesis II"
                };

                break;

            default:
                return;
        }

        actualizarCombo(combo1mer, m1);
        actualizarCombo(combo2do, m2);
        actualizarCombo(combo3cer, m3);
        actualizarCombo(combo4to, m4);
        actualizarCombo(combo5to, m5);

        redimensionar();
    }

    private void actualizarCombo(javax.swing.JComboBox<String> combo, String[] items) {
        combo.removeAllItems();
        for (String item : items) {
            combo.addItem(item);
        }
    }

    private void actualizarVisibilidadCombos() {
        if (labelTitulo == null || comboSubtitulo == null) {
            return;
        }

        String area = carreraSeleccionada;
        String subtitulo = (String) comboSubtitulo.getSelectedItem();

        boolean ocultarUltimos
                = "Áreas Curriculares: Medicina".equals(area)
                && ("Ciencias Básicas y biológicas".equals(subtitulo)
                || "Ciencias sociales y salud pública".equals(subtitulo)
                || "Investigación".equals(subtitulo));

        labelAnio4.setVisible(!ocultarUltimos);
        combo4to.setVisible(!ocultarUltimos);
        labelAnio5.setVisible(!ocultarUltimos);
        combo5to.setVisible(!ocultarUltimos);

        jPanel8.revalidate();
        jPanel8.repaint();
    }

    private void actualizarContenidoPorCarrera() {

        if (carreraSeleccionada == null) {
            return;
        }

        labelTitulo.setText(
                "Áreas Curriculares: "
                + carreraSeleccionada
        );

        comboSubtitulo.removeAllItems();

        switch (carreraSeleccionada) {

            case "Humanidades":

                agregarSubtitulos(
                        "Filosofía Antigua",
                        "Filosofía Moderna",
                        "Ética",
                        "Metafísica"
                );

                break;

            case "Económicas":

                agregarSubtitulos(
                        "Contabilidad",
                        "Economía",
                        "Mercadeo",
                        "Finanzas"
                );

                break;

            case "Ingenierías":

                agregarSubtitulos(
                        "Programación",
                        "Bases de Datos",
                        "Redes",
                        "Desarrollo"
                );

                break;

            case "Salud":

                agregarSubtitulos(
                        "Ciencias Básicas y biológicas",
                        "Ciencias sociales y salud pública",
                        "Ciencias Clínicas",
                        "Investigación"
                );

                break;

            case "Educación":

                agregarSubtitulos(
                        "Didáctica",
                        "Psicología Educativa",
                        "Currículo",
                        "Evaluación"
                );

                break;
        }

        comboSubtitulo.setSelectedIndex(0);

        actualizarMateriasPorSubtitulo();
    }

    private void agregarSubtitulos(String... datos) {

        for (String s : datos) {
            comboSubtitulo.addItem(s);
        }

    }

    private void redimensionar() {
        int ancho = getContentPane().getWidth();
        int alto = getContentPane().getHeight();

        // ── Panel de fondo ──
        jPanel5.setBounds(0, 0, ancho, alto);
        jPanel5.setLayout(null);

        // ── Barra superior ──
        jPanel6.setBounds(0, 0, ancho, 70);

        // ── Barra inferior ──
        jPanel7.setBounds(0, alto - 70, ancho, 70);

        // ── Panel central ──
        int anchoPanel = (int) (ancho * 0.70);
        int altoPanel = (int) (alto * 0.65);

        int xPanel = (ancho - anchoPanel) / 2;
        int yPanel = 170;
        jPanel8.setBounds(xPanel, yPanel, anchoPanel, altoPanel);
        jPanel8.setLayout(null);

        // ── ComboBox título (centrado) ──
        int anchoComboTitulo = (int) (anchoPanel * 0.42);
        int xComboTitulo = (anchoPanel - anchoComboTitulo) - 480;
        int anchoTitulo = (int) (anchoPanel * 0.60);

        labelTitulo.setBounds(
                (anchoPanel - anchoTitulo) / 2,
                40,
                anchoTitulo,
                50
        );

        labelTitulo.setFont(
                new java.awt.Font(
                        "Arial",
                        java.awt.Font.BOLD,
                        (int) (anchoPanel * 0.035)
                )
        );

        // ── comboSubtitulo ──
        if (comboSubtitulo != null) {
            int anchoSubtitulo = (int) (anchoPanel * 0.38);
            int xSubtitulo = (anchoPanel - anchoSubtitulo) / 2;
            comboSubtitulo.setBounds(xSubtitulo, 100, anchoSubtitulo, 40);
            comboSubtitulo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, (int) (anchoPanel * 0.016)));
        }

        // ── Columnas de años ──
        int margenIzq = (int) (anchoPanel * 0.03);
        int anchoColumna = (int) ((anchoPanel - margenIzq * 2) / 5.5);
        int separacion = (int) (anchoPanel * 0.020);
        int yLabel = (int) (altoPanel * 0.25);
        int yCombo = yLabel + 50;
        int altoCombo = (int) (altoPanel * 0.08);
        int tamFuente = Math.max(10, (int) (anchoColumna * 0.09));

        int[] xCols = new int[5];
        xCols[0] = margenIzq;
        for (int i = 1; i < 5; i++) {
            xCols[i] = xCols[i - 1] + anchoColumna + separacion;
        }

        // Labels de año
        javax.swing.JLabel[] labels = {
            labelAnio1,
            labelAnio2,
            labelAnio3,
            labelAnio4,
            labelAnio5
        };

        javax.swing.JComboBox[] combos = {
            combo1mer,
            combo2do,
            combo3cer,
            combo4to,
            combo5to
        };

        String[] nombres = {
            "1er Año",
            "2do Año",
            "3er Año",
            "4to Año",
            "5to Año"
        };

// Contar visibles
        int visibles = 0;

        for (javax.swing.JComboBox c : combos) {
            if (c.isVisible() && c.getItemCount() > 0) {
                visibles++;
            }
        }

        if (visibles > 0) {

            int anchoTotal
                    = (visibles * anchoColumna)
                    + ((visibles - 1) * separacion);

            int inicioX = (anchoPanel - anchoTotal) / 2;

            int pos = 0;

            for (int i = 0; i < combos.length; i++) {

                boolean mostrar
                        = combos[i].isVisible()
                        && combos[i].getItemCount() > 0;

                labels[i].setVisible(mostrar);
                combos[i].setVisible(mostrar);

                if (mostrar) {

                    int x = inicioX + pos * (anchoColumna + separacion);

                    labels[i].setText(nombres[i]);
                    labels[i].setFont(
                            new java.awt.Font(
                                    "Arial",
                                    java.awt.Font.BOLD,
                                    tamFuente
                            )
                    );

                    labels[i].setBounds(
                            x,
                            yLabel,
                            anchoColumna,
                            45
                    );

                    combos[i].setFont(
                            new java.awt.Font(
                                    "Arial",
                                    java.awt.Font.PLAIN,
                                    tamFuente
                            )
                    );

                    combos[i].setBounds(
                            x,
                            yCombo,
                            anchoColumna,
                            altoCombo
                    );

                    // ───── Botón Iniciar ─────
                    if (btnIniciar != null) {

                        int anchoBoton = (int) (anchoPanel * 0.20);
                        int altoBoton = 50;

                        btnIniciar.setBounds(
                                (anchoPanel - anchoBoton) / 2,
                                (altoPanel - altoBoton) / 2 + 200,
                                anchoBoton,
                                altoBoton
                        );

                        btnIniciar.setFont(new java.awt.Font(
                                "Arial",
                                java.awt.Font.BOLD,
                                Math.max(16, (int) (anchoPanel * 0.018))
                        ));
                    }

                    pos++;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
